version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - qdrant
      - redis
      - localstack
    environment:
      - DEBUG=true
      - DB_HOST=db
      - log_format=colored
      - db_echo=False
      - QDRANT_URL=qdrant
      - REDIS_URL=redis://redis:6379/0
      - AWS_ACCESS_KEY_ID=fake
      - AWS_SECRET_ACCESS_KEY=fake
      - AWS_ENDPOINT_URL=http://localstack:4566
    command:
      [ 'dev', '8000' ]

  db:
    image: postgres:latest
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"

  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=fake
      - AWS_SECRET_ACCESS_KEY=fake
      - SERVICES=s3
    ports:
      - '4566:4566'
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-/tmp/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./docker/localstack/setup.sh:/etc/localstack/init/ready.d/init-aws.sh"

networks:
  default:
    name: llm

volumes:
  db:
    driver: local
  qdrant_data:
    driver: local
