"""update bot documents

Revision ID: 7f4d489f48e5
Revises: 28159f9aeffc
Create Date: 2024-05-24 19:26:18.899334

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7f4d489f48e5"
down_revision: Union[str, None] = "28159f9aeffc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bot_documents", sa.Column("filename", sa.String(), nullable=True))
    op.add_column(
        "bot_documents", sa.Column("content_type", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bot_documents", "content_type")
    op.drop_column("bot_documents", "filename")
    # ### end Alembic commands ###
