name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11" ]
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: Gr1N/setup-poetry@v9
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - run: poetry --version
      - name: "Install dependencies"
        run: |
          poetry config virtualenvs.create false
          poetry install --no-interaction
      - name: "Lint"
        run: make lint

      - name: Install pytest annotation plugin
        run: poetry run pip install pytest-github-actions-annotate-failures

      - name: "Tests"
        run: make test

      - name: Upload coverage reports to Codecov with GitHub Action
        if: ${{ matrix.python-version == '3.11' && github.actor != 'dependabot[bot]' && github.actor != 'github-actions[bot]' }}
        uses: codecov/codecov-action@v4.4.0
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
